import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "en" | "hi";

const translations: Record<string, Record<Language, string>> = {
  "app.name": { en: "Mandi Mitra", hi: "मंडी मित्र" },
  "app.tagline": { en: "Agricultural Marketplace Manager", hi: "कृषि बाज़ार प्रबंधक" },
  "app.loading": { en: "Loading...", hi: "लोड हो रहा है..." },

  "nav.dashboard": { en: "Dashboard", hi: "डैशबोर्ड" },
  "dash.farmersLotsTxns": { en: "Farmers / Lots / Txns", hi: "किसान / लॉट / लेनदेन" },
  "dash.farmerPayable": { en: "Farmer Payable", hi: "किसान देय" },
  "dash.buyerReceivable": { en: "Buyer Receivable", hi: "खरीदार प्राप्य" },
  "dash.mandiCommission": { en: "Mandi Commission", hi: "मण्डी कमीशन" },
  "dash.aadhatCommission": { en: "Aadhat Commission", hi: "आढ़त कमीशन" },
  "dash.hammaliDue": { en: "Hammali Due", hi: "हम्माली बकाया" },
  "dash.hammali": { en: "Hammali", hi: "हम्माली" },
  "dash.hammaliExtra": { en: "Hammali | Extra", hi: "हम्माली | अतिरिक्त" },
  "dash.receivablesByCrop": { en: "Receivables by Crop", hi: "फसल अनुसार प्राप्य" },
  "dash.buyerDuesDist": { en: "Buyer Dues Distribution", hi: "खरीदार बकाया वितरण" },
  "dash.farmerDueByDate": { en: "Farmer Payable Due by Date", hi: "तारीख अनुसार किसान बकाया" },
  "dash.buyerDueByDate": { en: "Buyer Receivable Due by Date", hi: "तारीख अनुसार खरीदार बकाया" },
  "dash.volumeByDate": { en: "Total Volume (Kg) by Date", hi: "तारीख अनुसार कुल वज़न (Kg)" },
  "dash.aadhatByDate": { en: "Aadhat Value by Date", hi: "तारीख अनुसार आढ़त मूल्य" },
  "dash.allCrops": { en: "All Crops", hi: "सभी फसलें" },
  "dash.allYears": { en: "All Years", hi: "सभी वर्ष" },
  "dash.due": { en: "Due", hi: "बकाया" },
  "dash.noData": { en: "No data", hi: "कोई डेटा नहीं" },
  "dash.chargeSettings": { en: "Charge Settings", hi: "शुल्क सेटिंग्स" },
  "dash.mandiCommPct": { en: "Mandi Commission (%)", hi: "मण्डी कमीशन (%)" },
  "dash.aadhatCommPct": { en: "Aadhat Commission (%)", hi: "आढ़त कमीशन (%)" },
  "dash.muddatAnyaPct": { en: "Muddat + Anya (%)", hi: "मुद्दत + अन्य (%)" },
  "stock.muddatAnya": { en: "Muddat + Anya", hi: "मुद्दत + अन्य" },
  "dash.hammaliPerBag": { en: "Hammali (₹/bag)", hi: "हम्माली (₹/थैला)" },
  "dash.farmer": { en: "Farmer", hi: "किसान" },
  "dash.buyer": { en: "Buyer", hi: "खरीदार" },
  "dash.saveSettings": { en: "Save Settings", hi: "सेटिंग्स सहेजें" },
  "dash.saving": { en: "Saving...", hi: "सहेज रहे हैं..." },
  "dash.settingsSaved": { en: "Settings Saved", hi: "सेटिंग्स सहेजी गई" },
  "dash.settingsSavedDesc": { en: "Charge settings updated successfully", hi: "शुल्क सेटिंग्स सफलतापूर्वक अपडेट की गई" },
  "dash.error": { en: "Error", hi: "त्रुटि" },
  "dash.nYears": { en: "Years", hi: "वर्ष" },
  "dash.lineFarmerDue": { en: "Farmer Due", hi: "किसान बकाया" },
  "dash.lineBuyerDue": { en: "Buyer Due", hi: "खरीदार बकाया" },
  "dash.lineTotalVolume": { en: "Total Volume (Kg)", hi: "कुल वज़न (Kg)" },
  "dash.lineAadhatValue": { en: "Aadhat Value", hi: "आढ़त मूल्य" },
  "crop.potato": { en: "Potato", hi: "आलू" },
  "crop.onion": { en: "Onion", hi: "प्याज़" },
  "crop.garlic": { en: "Garlic", hi: "लहसुन" },
  "nav.dash": { en: "Dash", hi: "डैश" },
  "nav.bidding": { en: "Bidding", hi: "बोली" },
  "nav.cash": { en: "Cash", hi: "नकद" },
  "nav.farmerLedger": { en: "Farmer Ledger", hi: "किसान खाता" },
  "nav.buyerLedger": { en: "Buyer Ledger", hi: "खरीदार खाता" },
  "nav.farmers": { en: "Farmers", hi: "किसान" },
  "nav.buyers": { en: "Buyers", hi: "खरीदार" },
  "nav.books": { en: "Books", hi: "बही खाता" },
  "nav.assetRegister": { en: "Asset Register", hi: "संपत्ति रजिस्टर" },
  "nav.liabilityRegister": { en: "Liability Register", hi: "देनदारी रजिस्टर" },
  "nav.balanceSheet": { en: "Balance Sheet", hi: "तुलन पत्र" },
  "nav.profitLoss": { en: "Profit & Loss", hi: "लाभ और हानि" },
  "nav.demoVideos": { en: "Demo Videos", hi: "डेमो वीडियो" },
  "nav.demos": { en: "Demos", hi: "डेमो" },
  "nav.stock": { en: "Stock", hi: "स्टॉक" },
  "nav.more": { en: "More", hi: "और" },
  "nav.logout": { en: "Logout", hi: "लॉगआउट" },
  "nav.profile": { en: "Profile", hi: "प्रोफ़ाइल" },
  "profile.name": { en: "Name", hi: "नाम" },
  "profile.mobile": { en: "Mobile", hi: "मोबाइल" },
  "profile.merchant": { en: "Merchant", hi: "व्यापारी" },
  "profile.address": { en: "Address", hi: "पता" },
  "profile.accessType": { en: "Access Type", hi: "एक्सेस प्रकार" },
  "profile.editAccess": { en: "Edit Access", hi: "संपादन एक्सेस" },
  "profile.viewAccess": { en: "View Access", hi: "केवल देखें" },
  "profile.myBusinesses": { en: "My Businesses", hi: "मेरे व्यापार" },
  "profile.switch": { en: "Switch", hi: "बदलें" },

  "common.save": { en: "Save", hi: "सहेजें" },
  "common.saved": { en: "Saved", hi: "सहेज लिया" },
  "common.cancel": { en: "Cancel", hi: "रद्द करें" },
  "common.edit": { en: "Edit", hi: "संपादन" },
  "common.delete": { en: "Delete", hi: "हटाएं" },
  "common.search": { en: "Search", hi: "खोजें" },
  "common.saving": { en: "Saving...", hi: "सहेज रहे हैं..." },
  "common.date": { en: "Date", hi: "दिनांक" },
  "common.name": { en: "Name", hi: "नाम" },
  "common.phone": { en: "Phone", hi: "फ़ोन" },
  "common.contact": { en: "Contact", hi: "संपर्क" },
  "common.address": { en: "Address", hi: "पता" },
  "common.village": { en: "Village", hi: "गाँव" },
  "common.tehsil": { en: "Tehsil", hi: "तहसील" },
  "common.district": { en: "District", hi: "जिला" },
  "common.state": { en: "State", hi: "राज्य" },
  "common.yes": { en: "Yes", hi: "हाँ" },
  "common.no": { en: "No", hi: "नहीं" },
  "common.all": { en: "All", hi: "सभी" },
  "common.active": { en: "Active", hi: "सक्रिय" },
  "common.inactive": { en: "Inactive", hi: "निष्क्रिय" },
  "common.notes": { en: "Notes", hi: "नोट्स" },
  "common.optional": { en: "Optional", hi: "वैकल्पिक" },
  "common.saveChanges": { en: "Save Changes", hi: "बदलाव सहेजें" },
  "common.actions": { en: "Actions", hi: "कार्रवाई" },
  "common.flag": { en: "Flag", hi: "फ्लैग" },
  "common.bags": { en: "bags", hi: "थैले" },
  "common.remaining": { en: "Remaining", hi: "शेष" },
  "common.allMonths": { en: "All", hi: "सभी" },
  "common.allDays": { en: "All Days", hi: "सभी दिन" },
  "common.nMonths": { en: "months", hi: "माह" },
  "common.nDays": { en: "days", hi: "दिन" },
  "common.size": { en: "Size", hi: "साइज़" },
  "common.variety": { en: "Variety", hi: "किस्म" },
  "common.marka": { en: "Marka", hi: "मार्का" },

  "bidding.title": { en: "Bidding", hi: "बोली" },
  "bidding.bid": { en: "Bid", hi: "बोली" },
  "bidding.remainingBags": { en: "Remaining Bags", hi: "शेष थैले" },
  "bidding.existingBids": { en: "Existing Bids", hi: "मौजूदा बोलियाँ" },
  "bidding.newBid": { en: "New Bid", hi: "नई बोली" },
  "bidding.buyer": { en: "Buyer", hi: "खरीदार" },
  "bidding.selectBuyer": { en: "Select buyer", hi: "खरीदार चुनें" },
  "bidding.newBuyer": { en: "New Buyer", hi: "नया खरीदार" },
  "bidding.pricePerKg": { en: "Price/kg (Rs.)", hi: "दर/किलो (रु.)" },
  "bidding.numberOfBags": { en: "No. of Bags", hi: "थैलों की संख्या" },
  "bidding.addBid": { en: "Add Bid", hi: "बोली जोड़ें" },
  "bidding.noLots": { en: "No available lots for", hi: "कोई उपलब्ध लॉट नहीं" },
  "bidding.buyerName": { en: "Buyer name", hi: "खरीदार का नाम" },
  "bidding.phoneOptional": { en: "Phone (optional)", hi: "फ़ोन (वैकल्पिक)" },
  "bidding.redFlagWarningBuyer": { en: "It's a Red Flagged Buyer", hi: "यह रेड फ्लैग खरीदार है" },

  "transactions.title": { en: "Transactions", hi: "लेनदेन" },
  "transactions.editTransaction": { en: "Edit Transaction", hi: "लेनदेन संपादित करें" },
  "transactions.createTransaction": { en: "Create Transaction", hi: "लेनदेन बनाएं" },
  "transactions.selectBuyer": { en: "Select Buyer", hi: "खरीदार चुनें" },
  "transactions.totalWeight": { en: "Total Weight (kg)", hi: "कुल वजन (किलो)" },
  "transactions.netWeight": { en: "Net Weight (kg)", hi: "शुद्ध वजन (किलो)" },
  "transactions.hammali": { en: "Hammali (Rs./Bag)", hi: "हम्माली (रु./थैला)" },
  "transactions.extraCharges": { en: "Extra Charges (Rs.)", hi: "अतिरिक्त शुल्क (रु.)" },
  "transactions.aadhat": { en: "Aadhat %", hi: "आढ़त %" },
  "transactions.mandi": { en: "Mandi %", hi: "मण्डी %" },
  "transactions.buyer": { en: "Buyer", hi: "खरीदार" },
  "transactions.sellerFarmer": { en: "Seller (Farmer)", hi: "विक्रेता (किसान)" },
  "transactions.grossAmount": { en: "Gross Amount", hi: "कुल राशि" },
  "transactions.payableToFarmer": { en: "Payable to Farmer", hi: "किसान को देय" },
  "transactions.receivableFromBuyer": { en: "Receivable from Buyer", hi: "खरीदार से प्राप्य" },
  "transactions.updateTransaction": { en: "Update Transaction", hi: "लेनदेन अपडेट करें" },
  "transactions.returnToStockRegister": { en: "Return to Stock Register", hi: "स्टॉक रजिस्टर में वापसी" },
  "transactions.returnConfirmTitle": { en: "Return to Stock?", hi: "स्टॉक में वापस करें?" },
  "transactions.returnConfirmMsg": { en: "Are you sure you want to reverse this transaction?", hi: "क्या आप यह लेनदेन रद्द करना चाहते हैं?" },
  "transactions.yesReverse": { en: "Yes, Reverse", hi: "हाँ, रद्द करें" },
  "transactions.reversing": { en: "Reversing...", hi: "रद्द कर रहे हैं..." },
  "transactions.reversed": { en: "Reversed", hi: "रद्द" },
  "transactions.bidDeleted": { en: "Bid Removed", hi: "बोली हटाई गई" },
  "transactions.bidDeletedDesc": { en: "Bags returned to stock register", hi: "बैग स्टॉक रजिस्टर में वापस किए गए" },
  "transactions.bidReturnConfirmTitle": { en: "Return to Stock?", hi: "स्टॉक में वापस करें?" },
  "transactions.bidReturnConfirmMsg": { en: "Are you sure you want to remove this bid and return bags to stock?", hi: "क्या आप यह बोली हटाना और बैग स्टॉक में वापस करना चाहते हैं?" },
  "transactions.bidReturnBuyerInfo": { en: "Buyer: {buyer} — {bags} bags will be returned to stock and become available for bidding again.", hi: "खरीदार: {buyer} — {bags} बैग स्टॉक में वापस किए जाएंगे और फिर से बोली के लिए उपलब्ध होंगे।" },
  "transactions.yesReturn": { en: "Yes, Return", hi: "हाँ, वापस करें" },
  "transactions.returning": { en: "Returning...", hi: "वापस कर रहे हैं..." },
  "transactions.allMonths": { en: "All Months", hi: "सभी महीने" },
  "transactions.allDays": { en: "All Days", hi: "सभी दिन" },
  "transactions.allCrops": { en: "All Crops", hi: "सभी फसलें" },
  "transactions.farmer": { en: "Farmer", hi: "किसान" },
  "transactions.bagsTotal": { en: "bags total", hi: "कुल थैले" },
  "transactions.noBids": { en: "No bids or transactions yet. Complete bidding first.", hi: "अभी कोई बोली या लेनदेन नहीं। पहले बोली पूरी करें।" },
  "transactions.lot": { en: "Lot", hi: "लॉट" },

  "cash.title": { en: "Cash Management", hi: "नकद प्रबंधन" },
  "cash.subtitle": { en: "Track payments received and expenses", hi: "भुगतान प्राप्ति और खर्च ट्रैक करें" },
  "cash.buyer": { en: "Buyer", hi: "खरीदार" },
  "cash.farmer": { en: "Farmer", hi: "किसान" },
  "cash.others": { en: "Others", hi: "अन्य" },
  "cash.amount": { en: "Amount", hi: "राशि" },
  "cash.paymentMode": { en: "Payment Mode", hi: "भुगतान विधि" },
  "cash.noEntries": { en: "No cash flow entries yet", hi: "अभी तक कोई नकद प्रवाह एंट्री नहीं" },
  "cash.selectBuyer": { en: "Select buyer", hi: "खरीदार चुनें" },
  "cash.selectFarmer": { en: "Select farmer", hi: "किसान चुनें" },
  "cash.inward": { en: "Inflow", hi: "आवक" },
  "cash.outward": { en: "Outflow", hi: "जावक" },
  "cash.transfer": { en: "Transfer", hi: "हस्तांतरण" },
  "cash.inwardCash": { en: "Inward Cash", hi: "आवक नकद" },
  "cash.outwardCash": { en: "Outward Cash", hi: "जावक नकद" },
  "cash.outflowType": { en: "Outflow Type", hi: "जावक प्रकार" },
  "cash.farmerWithDues": { en: "Farmer (with dues)", hi: "किसान (बकाया सहित)" },
  "cash.filters": { en: "Filters", hi: "फ़िल्टर" },
  "cash.addBankFirst": { en: "Please add a bank account from Cash Settings before making transfers", hi: "ट्रांसफर करने से पहले कृपया कैश सेटिंग्स से बैंक खाता जोड़ें" },
  "cash.openSettings": { en: "Open Settings", hi: "सेटिंग्स खोलें" },
  "cash.cashFlowHistory": { en: "Cash Flow History", hi: "नकद प्रवाह इतिहास" },
  "cash.cashReceived": { en: "Cash Received", hi: "नकद प्राप्ति" },
  "cash.cashExpense": { en: "Cash Expense", hi: "नकद खर्च" },
  "cash.netCashInHand": { en: "Net Cash in Hand", hi: "हाथ में शेष नकद" },
  "cash.accountReceived": { en: "Account Received", hi: "खाता प्राप्ति" },
  "cash.accountExpense": { en: "Account Expense", hi: "खाता खर्च" },
  "cash.netInAccounts": { en: "Net in Accounts", hi: "खातों में शेष" },
  "cash.partyType": { en: "Party Type", hi: "पार्टी प्रकार" },
  "cash.buyerWithDues": { en: "Buyer (with dues)", hi: "खरीदार (बकाया सहित)" },
  "cash.paidOn": { en: "Paid On", hi: "भुगतान तिथि" },
  "cash.remarks": { en: "Remarks", hi: "टिप्पणी" },
  "cash.remarksPlaceholder": { en: "Any additional notes", hi: "अतिरिक्त नोट्स" },
  "cash.submit": { en: "Submit", hi: "जमा करें" },
  "cash.from": { en: "From", hi: "से" },
  "cash.to": { en: "To", hi: "को" },
  "cash.fromAccount": { en: "From Account", hi: "खाते से" },
  "cash.toAccount": { en: "To Account", hi: "खाते में" },
  "cash.selectAccount": { en: "Select account", hi: "खाता चुनें" },
  "cash.settings": { en: "Cash Settings", hi: "नकद सेटिंग्स" },
  "cash.cashInHandOpening": { en: "Cash in Hand (Opening Balance)", hi: "हाथ में नकद (प्रारंभिक शेष)" },
  "cash.bankAccounts": { en: "Bank Accounts", hi: "बैंक खाते" },
  "cash.addBankAccount": { en: "Add Bank Account", hi: "बैंक खाता जोड़ें" },
  "cash.addAccount": { en: "Add Account", hi: "खाता जोड़ें" },
  "cash.deleteAccount": { en: "Delete Bank Account", hi: "बैंक खाता हटाएं" },
  "cash.deleteAccountConfirm": { en: "Are you sure you want to delete the details of this bank account?", hi: "क्या आप इस बैंक खाते का विवरण हटाना चाहते हैं?" },
  "cash.bankAccount": { en: "Bank Account", hi: "बैंक खाता" },
  "cash.entryDetails": { en: "Entry Details", hi: "एंट्री विवरण" },
  "cash.category": { en: "Category", hi: "श्रेणी" },
  "cash.reverseEntry": { en: "Reverse Entry", hi: "एंट्री वापस करें" },
  "cash.reverseConfirm": { en: "This entry will be marked as reversed but not deleted. Are you sure?", hi: "यह एंट्री वापस चिह्नित की जाएगी लेकिन हटाई नहीं जाएगी। क्या आप सुनिश्चित हैं?" },
  "cash.reverse": { en: "Reverse", hi: "वापस करें" },
  "cash.partyName": { en: "Party Name", hi: "पार्टी नाम" },
  "cash.allParties": { en: "All Parties", hi: "सभी पार्टियां" },
  "cash.allTypes": { en: "All Types", hi: "सभी प्रकार" },

  "farmerLedger.title": { en: "Farmer Ledger", hi: "किसान खाता" },
  "farmerLedger.allYears": { en: "All Years", hi: "सभी वर्ष" },
  "farmerLedger.searchByName": { en: "Search By Name...", hi: "नाम से खोजें..." },
  "farmerLedger.searchByVillage": { en: "Search By Village...", hi: "गाँव से खोजें..." },
  "farmerLedger.showArchived": { en: "Show Archived", hi: "अभिलेख दिखाएं" },
  "farmerLedger.totalFarmers": { en: "Total Farmers", hi: "कुल किसान" },
  "farmerLedger.dueFarmers": { en: "# Due Farmers", hi: "बकाया किसान" },
  "farmerLedger.totalPayable": { en: "Total Payable", hi: "कुल देय" },
  "farmerLedger.totalDues": { en: "Total Dues", hi: "कुल बकाया" },
  "farmerLedger.farmerId": { en: "Farmer ID", hi: "किसान ID" },
  "farmerLedger.totalDue": { en: "Total Due", hi: "कुल बकाया" },
  "farmerLedger.editFarmer": { en: "Edit Farmer", hi: "किसान संपादित करें" },
  "farmerLedger.editDesc": { en: "Update farmer details. Duplicate detection will trigger merge if a match is found.", hi: "किसान विवरण अपडेट करें। डुप्लिकेट पाए जाने पर मर्ज होगा।" },
  "farmerLedger.redFlag": { en: "Red Flag", hi: "रेड फ्लैग" },
  "farmerLedger.editHistory": { en: "Edit History", hi: "संपादन इतिहास" },
  "farmerLedger.noFarmers": { en: "No farmers found", hi: "कोई किसान नहीं मिला" },
  "farmerLedger.noArchived": { en: "No archived farmers found", hi: "कोई अभिलेख किसान नहीं मिला" },
  "farmerLedger.loadingFarmers": { en: "Loading farmers...", hi: "किसान लोड हो रहे हैं..." },
  "farmerLedger.reinstate": { en: "Reinstate", hi: "बहाल करें" },
  "farmerLedger.archive": { en: "Archive", hi: "अभिलेख" },

  "buyerLedger.title": { en: "Buyer Ledger", hi: "खरीदार खाता" },
  "buyerLedger.subtitle": { en: "Manage buyers and track dues", hi: "खरीदारों का प्रबंधन और बकाया ट्रैक करें" },
  "buyerLedger.buyerManagement": { en: "Buyer Management", hi: "खरीदार प्रबंधन" },
  "buyerLedger.searchName": { en: "Search Name...", hi: "नाम खोजें..." },
  "buyerLedger.addBuyer": { en: "Add Buyer", hi: "खरीदार जोड़ें" },
  "buyerLedger.buyerId": { en: "Buyer ID", hi: "खरीदार ID" },
  "buyerLedger.mandiCode": { en: "Licence No", hi: "लाइसेंस नं." },
  "buyerLedger.redFlag": { en: "Red Flag", hi: "रेड फ्लैग" },
  "buyerLedger.overallDue": { en: "Overall Due", hi: "कुल बकाया" },
  "buyerLedger.receivables": { en: "Receivables", hi: "प्राप्य" },
  "buyerLedger.editBuyer": { en: "Edit Buyer", hi: "खरीदार संपादित करें" },
  "buyerLedger.buyerCode": { en: "Licence No", hi: "लाइसेंस नं." },
  "buyerLedger.openingBalance": { en: "Opening Balance", hi: "शुरुआती शेष" },
  "buyerLedger.redFlagLabel": { en: "Red Flag", hi: "रेड फ्लैग" },
  "buyerLedger.editHistory": { en: "Edit History", hi: "संपादन इतिहास" },
  "buyerLedger.addNewBuyer": { en: "Add New Buyer", hi: "नया खरीदार जोड़ें" },
  "buyerLedger.noBuyers": { en: "No buyers found", hi: "कोई खरीदार नहीं मिला" },
  "buyerLedger.overall": { en: "Overall", hi: "कुल" },
  "buyerLedger.receivable": { en: "Receivable", hi: "प्राप्य" },
  "buyerLedger.aadhatCommission": { en: "Aadhat Commission %", hi: "आढ़त कमीशन %" },
  "buyerLedger.aadhatCommissionHint": { en: "Leave blank to use default from Dashboard settings", hi: "डैशबोर्ड सेटिंग्स का डिफ़ॉल्ट उपयोग करने के लिए खाली छोड़ें" },
  "buyerLedger.adding": { en: "Adding...", hi: "जोड़ रहे हैं..." },
  "buyerLedger.totalBuyers": { en: "Total Buyers", hi: "कुल खरीदार" },
  "buyerLedger.buyersWithDues": { en: "With Dues", hi: "बकाया वाले" },
  "buyerLedger.totalOverallDue": { en: "Overall Due", hi: "कुल बकाया" },
  "buyerLedger.totalReceivableDue": { en: "Receivable Due", hi: "प्राप्य बकाया" },
  "buyerLedger.duesOver30": { en: "Dues > 30 Days", hi: "बकाया > 30 दिन" },
  "buyerLedger.duesOver15": { en: "Dues > 15 Days", hi: "बकाया > 15 दिन" },
  "buyerLedger.allYears": { en: "All Years", hi: "सभी वर्ष" },

  "login.title": { en: "Mandi Mitra", hi: "मंडी मित्र" },
  "login.userName": { en: "User Name", hi: "उपयोगकर्ता नाम" },
  "login.password": { en: "Password", hi: "पासवर्ड" },
  "login.login": { en: "Login", hi: "लॉगिन" },
  "login.signingIn": { en: "Signing in...", hi: "लॉगिन हो रहा है..." },
  "login.changePassword": { en: "Change Password", hi: "पासवर्ड बदलें" },
  "login.needHelp": { en: "Need Help? Please reach out to", hi: "मदद चाहिए? कृपया संपर्क करें" },
  "login.captchaRequired": { en: "Please complete the CAPTCHA verification", hi: "कृपया CAPTCHA सत्यापन पूरा करें" },
  "login.captchaFailed": { en: "CAPTCHA verification failed. Please try again.", hi: "CAPTCHA सत्यापन विफल हुआ। कृपया पुनः प्रयास करें।" },
  "login.enterUsername": { en: "Enter Your Username", hi: "अपना उपयोगकर्ता नाम दर्ज करें" },
  "login.enterPassword": { en: "Enter password", hi: "पासवर्ड दर्ज करें" },

  "changePassword.title": { en: "Change Password", hi: "पासवर्ड बदलें" },
  "changePassword.registeredMobile": { en: "Registered Mobile Number", hi: "पंजीकृत मोबाइल नंबर" },
  "changePassword.currentPassword": { en: "Current Password", hi: "वर्तमान पासवर्ड" },
  "changePassword.newPassword": { en: "New Password", hi: "नया पासवर्ड" },
  "changePassword.confirmPassword": { en: "Confirm Password", hi: "पासवर्ड पुष्टि करें" },
  "changePassword.setNew": { en: "Set New Password", hi: "नया पासवर्ड सेट करें" },
  "changePassword.changing": { en: "Changing...", hi: "बदल रहे हैं..." },
  "changePassword.backToLogin": { en: "Back to Login", hi: "लॉगिन पर वापस जाएं" },
  "changePassword.forgotPassword": { en: "Forgot your password? Please contact", hi: "पासवर्ड भूल गए? कृपया संपर्क करें" },
  "changePassword.enterMobile": { en: "Enter your registered mobile number", hi: "अपना पंजीकृत मोबाइल नंबर दर्ज करें" },
  "changePassword.enterCurrent": { en: "Enter your current password", hi: "अपना वर्तमान पासवर्ड दर्ज करें" },
  "changePassword.enterNew": { en: "Enter new password", hi: "नया पासवर्ड दर्ज करें" },
  "changePassword.confirmNew": { en: "Confirm new password", hi: "नया पासवर्ड पुष्टि करें" },
  "changePassword.enterUsername": { en: "Enter your username", hi: "अपना उपयोगकर्ता नाम दर्ज करें" },

  "admin.title": { en: "Admin Panel", hi: "एडमिन पैनल" },
  "admin.subtitle": { en: "Manage merchants and users", hi: "व्यापारी और उपयोगकर्ता प्रबंधित करें" },
  "admin.merchants": { en: "Merchants", hi: "व्यापारी" },
  "admin.users": { en: "Users", hi: "उपयोगकर्ता" },
  "admin.addMerchant": { en: "Add Merchant", hi: "व्यापारी जोड़ें" },
  "admin.searchMerchants": { en: "Search Merchants...", hi: "व्यापारी खोजें..." },
  "admin.merchantId": { en: "Merchant ID", hi: "व्यापारी ID" },
  "admin.businessName": { en: "Business Name *", hi: "व्यापार का नाम *" },
  "admin.contactNumber": { en: "Contact Number", hi: "संपर्क नंबर" },
  "admin.status": { en: "Status", hi: "स्थिति" },
  "admin.editMerchant": { en: "Edit Merchant", hi: "व्यापारी संपादित करें" },
  "admin.createMerchant": { en: "Create a new merchant/business account", hi: "नया व्यापारी/व्यापार खाता बनाएं" },
  "admin.updateMerchant": { en: "Update merchant details for", hi: "व्यापारी विवरण अपडेट करें" },
  "admin.update": { en: "Update", hi: "अपडेट" },
  "admin.confirm": { en: "Confirm", hi: "पुष्टि करें" },
  "admin.processing": { en: "Processing...", hi: "प्रक्रिया में..." },
  "admin.adminPassword": { en: "Admin Password *", hi: "एडमिन पासवर्ड *" },
  "admin.resetPassword": { en: "Reset Password *", hi: "रीसेट पासवर्ड *" },
  "admin.searchUsers": { en: "Search Users...", hi: "उपयोगकर्ता खोजें..." },
  "admin.addUser": { en: "Add User", hi: "उपयोगकर्ता जोड़ें" },
  "admin.noMerchants": { en: "No merchants found", hi: "कोई व्यापारी नहीं मिला" },
  "admin.noUsers": { en: "No users found", hi: "कोई उपयोगकर्ता नहीं मिला" },
  "admin.manageMerchants": { en: "Manage all registered merchants/businesses", hi: "सभी पंजीकृत व्यापारी/व्यापार प्रबंधित करें" },
  "admin.manageUsers": { en: "Manage all user accounts", hi: "सभी उपयोगकर्ता खाते प्रबंधित करें" },

  "language.english": { en: "English", hi: "English" },
  "language.hindi": { en: "हिंदी", hi: "हिंदी" },

  "demoVideos.title": { en: "Demo Videos", hi: "डेमो वीडियो" },
  "demoVideos.subtitle": { en: "Watch demo videos to learn how to use the app", hi: "ऐप का उपयोग सीखने के लिए डेमो वीडियो देखें" },
  "demoVideos.noVideos": { en: "No demo videos available yet", hi: "अभी कोई डेमो वीडियो उपलब्ध नहीं है" },
  "demoVideos.upload": { en: "Upload Video", hi: "वीडियो अपलोड करें" },
  "demoVideos.caption": { en: "Caption", hi: "शीर्षक" },
  "demoVideos.captionPlaceholder": { en: "Enter video caption", hi: "वीडियो शीर्षक दर्ज करें" },
  "demoVideos.uploading": { en: "Uploading...", hi: "अपलोड हो रहा है..." },
  "demoVideos.deleteConfirm": { en: "Delete this video?", hi: "यह वीडियो हटाएं?" },
  "demoVideos.manageVideos": { en: "Upload and manage demo videos for users", hi: "उपयोगकर्ताओं के लिए डेमो वीडियो अपलोड और प्रबंधित करें" },

  "books.title": { en: "Books", hi: "बही खाता" },
  "books.beta": { en: "Beta", hi: "बीटा" },
  "assets.title": { en: "Asset Register", hi: "संपत्ति रजिस्टर" },
  "assets.addAsset": { en: "Add Asset", hi: "संपत्ति जोड़ें" },
  "assets.editAsset": { en: "Edit Asset", hi: "संपत्ति संपादन" },
  "assets.name": { en: "Asset Name", hi: "संपत्ति नाम" },
  "assets.category": { en: "Category", hi: "श्रेणी" },
  "assets.purchaseDate": { en: "Purchase Date", hi: "खरीद तिथि" },
  "assets.originalCost": { en: "Original Cost", hi: "मूल लागत" },
  "assets.bookValue": { en: "Book Value", hi: "पुस्तक मूल्य" },
  "assets.depRate": { en: "Depreciation Rate (%)", hi: "मूल्यह्रास दर (%)" },
  "assets.type": { en: "Type", hi: "प्रकार" },
  "assets.opening": { en: "Opening", hi: "शुरुआती" },
  "assets.disposed": { en: "Disposed", hi: "निपटान" },
  "assets.active": { en: "Active", hi: "सक्रिय" },
  "assets.dispose": { en: "Dispose", hi: "निपटान करें" },
  "assets.disposalDate": { en: "Disposal Date", hi: "निपटान तिथि" },
  "assets.disposalAmount": { en: "Disposal Amount", hi: "निपटान राशि" },
  "assets.disposalReason": { en: "Reason", hi: "कारण" },
  "assets.runDepreciation": { en: "Run Depreciation", hi: "मूल्यह्रास चलाएं" },
  "assets.depLog": { en: "Depreciation Log", hi: "मूल्यह्रास लॉग" },
  "assets.fy": { en: "Financial Year", hi: "वित्तीय वर्ष" },
  "assets.openingVal": { en: "Opening Value", hi: "शुरुआती मूल्य" },
  "assets.depAmount": { en: "Depreciation", hi: "मूल्यह्रास" },
  "assets.closingVal": { en: "Closing Value", hi: "अंतिम मूल्य" },
  "assets.months": { en: "Months", hi: "महीने" },
  "assets.noAssets": { en: "No assets found", hi: "कोई संपत्ति नहीं मिली" },
  "assets.deleteConfirm": { en: "Delete this asset?", hi: "यह संपत्ति हटाएं?" },
  "assets.selectFY": { en: "Select FY", hi: "वित्तीय वर्ष चुनें" },
  "assets.depSuccess": { en: "Depreciation calculated successfully", hi: "मूल्यह्रास सफलतापूर्वक गणना की गई" },

  "liabilities.title": { en: "Liability Register", hi: "देनदारी रजिस्टर" },
  "liabilities.addLiability": { en: "Add Liability", hi: "देनदारी जोड़ें" },
  "liabilities.editLiability": { en: "Edit Liability", hi: "देनदारी संपादन" },
  "liabilities.name": { en: "Name", hi: "नाम" },
  "liabilities.type": { en: "Type", hi: "प्रकार" },
  "liabilities.originalAmount": { en: "Original Amount", hi: "मूल राशि" },
  "liabilities.outstanding": { en: "Outstanding", hi: "बकाया" },
  "liabilities.interestRate": { en: "Interest Rate (%)", hi: "ब्याज दर (%)" },
  "liabilities.emi": { en: "EMI Amount", hi: "EMI राशि" },
  "liabilities.startDate": { en: "Start Date", hi: "प्रारंभ तिथि" },
  "liabilities.settled": { en: "Settled", hi: "निपटान" },
  "liabilities.markSettled": { en: "Mark Settled", hi: "निपटान करें" },
  "liabilities.payments": { en: "Payments", hi: "भुगतान" },
  "liabilities.addPayment": { en: "Add Payment", hi: "भुगतान जोड़ें" },
  "liabilities.paymentDate": { en: "Payment Date", hi: "भुगतान तिथि" },
  "liabilities.amount": { en: "Amount", hi: "राशि" },
  "liabilities.principal": { en: "Principal", hi: "मूलधन" },
  "liabilities.interest": { en: "Interest", hi: "ब्याज" },
  "liabilities.reverse": { en: "Reverse", hi: "उलटना" },
  "liabilities.reversed": { en: "Reversed", hi: "उलट दिया" },
  "liabilities.noLiabilities": { en: "No liabilities found", hi: "कोई देनदारी नहीं मिली" },
  "liabilities.deleteConfirm": { en: "Delete this liability?", hi: "यह देनदारी हटाएं?" },

  "balanceSheet.title": { en: "Balance Sheet", hi: "तुलन पत्र" },
  "balanceSheet.asOf": { en: "As of March 31", hi: "31 मार्च तक" },
  "balanceSheet.fixedAssets": { en: "Fixed Assets", hi: "स्थायी संपत्ति" },
  "balanceSheet.currentAssets": { en: "Current Assets", hi: "चालू संपत्ति" },
  "balanceSheet.cashInHand": { en: "Cash in Hand", hi: "नकदी" },
  "balanceSheet.bankBalances": { en: "Bank Balances", hi: "बैंक शेष" },
  "balanceSheet.farmerReceivable": { en: "Farmer Receivables", hi: "किसान प्राप्य" },
  "balanceSheet.farmerPayable": { en: "Farmer Payable", hi: "किसान देय" },
  "balanceSheet.buyerReceivable": { en: "Buyer Receivables", hi: "खरीदार प्राप्य" },
  "balanceSheet.totalAssets": { en: "Total Assets", hi: "कुल संपत्ति" },
  "balanceSheet.longTermLiabilities": { en: "Long-term Liabilities", hi: "दीर्घकालिक देनदारी" },
  "balanceSheet.currentLiabilities": { en: "Current Liabilities", hi: "चालू देनदारी" },
  "balanceSheet.limitOutstanding": { en: "Limit A/c Outstanding", hi: "लिमिट खाता बकाया" },
  "balanceSheet.totalLiabilities": { en: "Total Liabilities", hi: "कुल देनदारी" },
  "balanceSheet.ownersEquity": { en: "Owner's Equity", hi: "मालिक की पूंजी" },
  "balanceSheet.downloadCSV": { en: "Download CSV", hi: "CSV डाउनलोड" },

  "pnl.title": { en: "Profit & Loss", hi: "लाभ और हानि" },
  "pnl.income": { en: "Income", hi: "आय" },
  "pnl.aadhatCommission": { en: "Aadhat Commission", hi: "आढ़त कमीशन" },
  "pnl.mandiCommission": { en: "Mandi Commission", hi: "मण्डी कमीशन" },
  "pnl.hammaliIncome": { en: "Hammali Income", hi: "हम्माली आय" },
  "pnl.extraCharges": { en: "Extra Charges", hi: "अतिरिक्त शुल्क" },
  "pnl.totalIncome": { en: "Total Income", hi: "कुल आय" },
  "pnl.expenses": { en: "Expenses", hi: "व्यय" },
  "pnl.depreciation": { en: "Depreciation", hi: "मूल्यह्रास" },
  "pnl.interestOnLiabilities": { en: "Interest on Liabilities", hi: "देनदारी पर ब्याज" },
  "pnl.totalExpenses": { en: "Total Expenses", hi: "कुल व्यय" },
  "pnl.netProfitLoss": { en: "Net Profit / Loss", hi: "शुद्ध लाभ / हानि" },
  "pnl.profit": { en: "Profit", hi: "लाभ" },
  "pnl.loss": { en: "Loss", hi: "हानि" },
  "pnl.downloadCSV": { en: "Download CSV", hi: "CSV डाउनलोड" },
  "pnl.forFY": { en: "For FY", hi: "वित्तीय वर्ष" },

  "stock.title": { en: "Mandi Stock", hi: "मंडी स्टॉक" },
  "stock.subtitle": { en: "Add farmers, lots, bids and weights in one place", hi: "एक जगह किसान, लॉट, बोली और वजन जोड़ें" },
  "stock.loading": { en: "Loading stock entries...", hi: "स्टॉक एंट्री लोड हो रही हैं..." },
  "stock.newFarmerEntry": { en: "New Farmer Entry", hi: "नई किसान एंट्री" },
  "stock.farmerDetails": { en: "Farmer Details", hi: "किसान विवरण" },
  "stock.vehicleInfo": { en: "Vehicle Info", hi: "वाहन जानकारी" },
  "stock.weightCharges": { en: "Weight & Charges", hi: "वजन और शुल्क" },
  "stock.bidTxnDetails": { en: "Bid & Transaction Details", hi: "बोली और लेनदेन विवरण" },
  "stock.farmerCharges": { en: "Farmer Charges", hi: "किसान शुल्क" },
  "stock.buyerCharges": { en: "Buyer Charges", hi: "खरीदार शुल्क" },
  "stock.netWeight": { en: "Net Weight (kg)", hi: "शुद्ध वजन (किलो)" },
  "stock.calcWt": { en: "Calc Wt", hi: "वजन गणना" },
  "stock.total": { en: "Total", hi: "कुल" },
  "stock.avgWeight": { en: "Avg Weight", hi: "औसत वजन" },
  "stock.sampleBagWeights": { en: "Sample Bag Weights (kg)", hi: "नमूना थैला वजन (किलो)" },
  "stock.over100kg": { en: "Over 100kg", hi: "100 किलो से अधिक" },
  "stock.addSample": { en: "Add Sample", hi: "नमूना जोड़ें" },
  "stock.average": { en: "Average", hi: "औसत" },
  "stock.samples": { en: "samples", hi: "नमूने" },
  "stock.aadhat": { en: "Aadhat", hi: "आढ़त" },
  "stock.mandi": { en: "Mandi", hi: "मण्डी" },
  "stock.hammali": { en: "Hammali", hi: "हम्माली" },
  "stock.freight": { en: "Freight", hi: "भाड़ा" },
  "stock.freightAuto": { en: "Freight (auto)", hi: "भाड़ा (स्वचालित)" },
  "stock.extra": { en: "Extra", hi: "अतिरिक्त" },
  "stock.extraPerKg": { en: "Extra ₹/Kg", hi: "अतिरिक्त ₹/किलो" },
  "stock.gross": { en: "Gross", hi: "कुल" },
  "stock.deductions": { en: "Deductions", hi: "कटौती" },
  "stock.additions": { en: "Additions", hi: "जोड़" },
  "stock.noDeductions": { en: "No deductions", hi: "कोई कटौती नहीं" },
  "stock.noAdditions": { en: "No additions", hi: "कोई जोड़ नहीं" },
  "stock.farmerPayable": { en: "Farmer Payable", hi: "किसान देय" },
  "stock.buyerReceivable": { en: "Buyer Receivable", hi: "खरीदार प्राप्य" },
  "stock.farmerRate": { en: "Farmer Rate", hi: "किसान दर" },
  "stock.buyerRate": { en: "Buyer Rate", hi: "खरीदार दर" },
  "stock.tulai": { en: "Tulai", hi: "तुलाई" },
  "stock.bharai": { en: "Bharai", hi: "भराई" },
  "stock.khadiKarai": { en: "Khadi Karai", hi: "खड़ी कराई" },
  "stock.thelaBhada": { en: "Thela Bhada", hi: "ठेला भाड़ा" },
  "stock.others": { en: "Others", hi: "अन्य" },
  "stock.txnDate": { en: "Txn Date", hi: "लेनदेन तिथि" },
  "stock.reset": { en: "Reset", hi: "रीसेट" },
  "stock.buyer": { en: "Buyer", hi: "खरीदार" },
  "stock.selectBuyer": { en: "Select buyer…", hi: "खरीदार चुनें…" },
  "stock.selectFromList": { en: "Select a buyer from the list", hi: "सूची से खरीदार चुनें" },
  "stock.pricePerKg": { en: "Price / kg (₹)", hi: "दर / किलो (₹)" },
  "stock.numBags": { en: "# Bags", hi: "# थैले" },
  "stock.numBagsReq": { en: "# Bags *", hi: "# थैले *" },
  "stock.exceedsLotBags": { en: "Exceeds lot bags", hi: "लॉट थैलों से अधिक" },
  "stock.payment": { en: "Payment", hi: "भुगतान" },
  "stock.credit": { en: "Credit", hi: "उधार" },
  "stock.cash": { en: "Cash", hi: "नकद" },
  "stock.cashAdvance": { en: "Cash advance ₹", hi: "नकद अग्रिम ₹" },
  "stock.addBid": { en: "Add Bid", hi: "बोली जोड़ें" },
  "stock.noBids": { en: "No bids. Add one below.", hi: "कोई बोली नहीं। नीचे जोड़ें।" },
  "stock.lot": { en: "Lot", hi: "लॉट" },
  "stock.bagMarka": { en: "Bag Marka", hi: "बैग मार्का" },
  "stock.none": { en: "None", hi: "कोई नहीं" },
  "stock.addLotUnder": { en: "Add Lot under", hi: "लॉट जोड़ें" },
  "stock.deleteThisLot": { en: "Delete this lot?", hi: "यह लॉट हटाएं?" },
  "stock.deleteLotOnlyDesc": { en: "This is the only lot. Deleting it will permanently remove this lot. The group will remain.", hi: "यह एकमात्र लॉट है। इसे हटाने से यह लॉट स्थायी रूप से हटा दिया जाएगा। समूह बना रहेगा।" },
  "stock.deleteLotDataDesc": { en: "has data that will be permanently lost. This action cannot be undone.", hi: "में डेटा है जो स्थायी रूप से खो जाएगा। यह क्रिया पूर्ववत नहीं की जा सकती।" },
  "stock.lots": { en: "lots", hi: "लॉट" },
  "stock.archived": { en: "Archived", hi: "अभिलेखित" },
  "stock.reinstate": { en: "Reinstate", hi: "बहाल करें" },
  "stock.reinstateDesc": { en: "All lots, bids, and payment details for this crop group will be included in calculations again, including dues and payments.", hi: "इस फसल समूह के सभी लॉट, बोलियां और भुगतान विवरण फिर से गणना में शामिल किए जाएंगे, जिसमें बकाया और भुगतान शामिल हैं।" },
  "stock.printShareReceipt": { en: "Print / Share Receipt", hi: "रसीद प्रिंट / शेयर करें" },
  "stock.printFarmerReceipt": { en: "Print किसान रसीद", hi: "प्रिंट किसान रसीद" },
  "stock.shareFarmerReceipt": { en: "Share किसान रसीद", hi: "शेयर किसान रसीद" },
  "stock.printReceipt": { en: "Print", hi: "प्रिंट" },
  "stock.shareReceipt": { en: "Share", hi: "शेयर" },
  "stock.receipt": { en: "Receipt", hi: "रसीद" },
  "stock.editHistory": { en: "Edit History", hi: "संपादन इतिहास" },
  "stock.archiveCropGroup": { en: "Archive this crop group", hi: "इस फसल समूह को अभिलेखित करें" },
  "stock.deleteCropGroup": { en: "Delete this crop group", hi: "यह फसल समूह हटाएं" },
  "stock.noChangesYet": { en: "No changes recorded yet. History is tracked after the first Save Entry.", hi: "अभी तक कोई बदलाव दर्ज नहीं। इतिहास पहली सेव एंट्री के बाद ट्रैक किया जाता है।" },
  "stock.entrySaved": { en: "Entry saved", hi: "एंट्री सहेजी गई" },
  "stock.by": { en: "by", hi: "द्वारा" },
  "stock.close": { en: "Close", hi: "बंद करें" },
  "stock.deleted": { en: "deleted", hi: "हटाया गया" },
  "stock.added": { en: "added", hi: "जोड़ा गया" },
  "stock.unsavedChanges": { en: "Unsaved Changes", hi: "असहेजे बदलाव" },
  "stock.hasUnsavedChanges": { en: "has unsaved changes.", hi: "में असहेजे बदलाव हैं।" },
  "stock.thisEntryUnsaved": { en: "This entry has unsaved changes.", hi: "इस एंट्री में असहेजे बदलाव हैं।" },
  "stock.whatToDo": { en: "What would you like to do?", hi: "आप क्या करना चाहेंगे?" },
  "stock.keepEditing": { en: "Keep Editing", hi: "संपादन जारी रखें" },
  "stock.discardClose": { en: "Discard & Close", hi: "छोड़ें और बंद करें" },
  "stock.saveClose": { en: "Save & Close", hi: "सहेजें और बंद करें" },
  "stock.due": { en: "Due", hi: "बकाया" },
  "stock.paid": { en: "Paid", hi: "भुगतान हुआ" },
  "stock.partialPaid": { en: "Partial Paid", hi: "आंशिक भुगतान" },
  "stock.totalBags": { en: "Total Bags", hi: "कुल थैले" },
  "stock.remaining": { en: "Remaining", hi: "शेष" },
  "stock.farmer": { en: "Farmer", hi: "किसान" },
  "stock.archivedExcluded": { en: "Archived — excluded from all calculations", hi: "अभिलेखित — सभी गणनाओं से बाहर" },
  "stock.archiveFarmerEntry": { en: "Archive this farmer entry", hi: "इस किसान एंट्री को अभिलेखित करें" },
  "stock.advance": { en: "Advance", hi: "अग्रिम" },
  "stock.farmerName": { en: "Name *", hi: "नाम *" },
  "stock.farmerNamePlaceholder": { en: "Farmer name", hi: "किसान का नाम" },
  "stock.phone": { en: "Phone", hi: "फ़ोन" },
  "stock.phonePlaceholder": { en: "10-digit mobile", hi: "10 अंकों का मोबाइल" },
  "stock.phoneWarning": { en: "Please provide a valid 10-digit number", hi: "कृपया एक वैध 10 अंकों का नंबर दें" },
  "stock.selectDistrict": { en: "Select district", hi: "जिला चुनें" },
  "stock.searchDistrict": { en: "Search district...", hi: "जिला खोजें..." },
  "stock.noDistrictFound": { en: "No district found.", hi: "कोई जिला नहीं मिला।" },
  "stock.selectState": { en: "Select state", hi: "राज्य चुनें" },
  "stock.farmerAdvance": { en: "Farmer Advance ₹", hi: "किसान अग्रिम ₹" },
  "stock.mode": { en: "Mode", hi: "विधि" },
  "stock.select": { en: "Select", hi: "चुनें" },
  "stock.account": { en: "Account", hi: "खाता" },
  "stock.vehicleNo": { en: "Vehicle #", hi: "वाहन नं." },
  "stock.driverName": { en: "Driver Name", hi: "ड्राइवर नाम" },
  "stock.driverContact": { en: "Driver Contact", hi: "ड्राइवर संपर्क" },
  "stock.optional": { en: "Optional", hi: "वैकल्पिक" },
  "stock.freightBhada": { en: "Freight/Bhada (₹)", hi: "भाड़ा (₹)" },
  "stock.advanceCredit": { en: "Advance / Credit", hi: "अग्रिम / उधार" },
  "stock.selectType": { en: "Select type", hi: "प्रकार चुनें" },
  "stock.totalBagsVehicle": { en: "Total # of Bags", hi: "कुल थैलों की संख्या" },
  "stock.allocated": { en: "Allocated", hi: "आवंटित" },
  "stock.selectCropToBegin": { en: "Select a crop above to begin adding lots", hi: "लॉट जोड़ना शुरू करने के लिए ऊपर एक फसल चुनें" },
  "stock.cancelEntry": { en: "Cancel", hi: "रद्द करें" },
  "stock.lastSaved": { en: "Last saved", hi: "आखिरी बार सहेजा" },
  "stock.saveEntry": { en: "Save Entry", hi: "एंट्री सहेजें" },
  "stock.archiveConfirmDesc": { en: "This farmer entry will be archived and excluded from all calculations.", hi: "इस किसान एंट्री को अभिलेखित किया जाएगा और सभी गणनाओं से बाहर रखा जाएगा।" },
  "stock.archiveGroupConfirmDesc": { en: "This crop group will be archived and excluded from all calculations.", hi: "इस फसल समूह को अभिलेखित किया जाएगा और सभी गणनाओं से बाहर रखा जाएगा।" },
  "stock.reinstateDesc2": { en: "This farmer entry and all its crop groups, lots, and bids will be included in all calculations again, including dues and payments.", hi: "इस किसान एंट्री और इसके सभी फसल समूह, लॉट, और बोलियां फिर से सभी गणनाओं में शामिल की जाएंगी, जिसमें बकाया और भुगतान शामिल हैं।" },
  "stock.deleteGroupConfirm": { en: "This crop group has data that will be permanently lost. This action cannot be undone.", hi: "इस फसल समूह में डेटा है जो स्थायी रूप से खो जाएगा। यह क्रिया पूर्ववत नहीं की जा सकती।" },
  "stock.yesDelete": { en: "Yes, Delete", hi: "हाँ, हटाएं" },
  "stock.yesArchive": { en: "Yes, Archive", hi: "हाँ, अभिलेखित करें" },
  "stock.yesReinstate": { en: "Yes, Reinstate", hi: "हाँ, बहाल करें" },
  "stock.filterStock": { en: "Stock", hi: "स्टॉक" },
  "stock.filterTxn": { en: "Txn", hi: "लेनदेन" },
  "stock.allYears": { en: "All Years", hi: "सभी वर्ष" },
  "stock.allMonths": { en: "All Months", hi: "सभी महीने" },
  "stock.allDays": { en: "All Days", hi: "सभी दिन" },
  "stock.nMonths": { en: "Months", hi: "महीने" },
  "stock.nDays": { en: "Days", hi: "दिन" },
  "stock.allCrops": { en: "All Crops", hi: "सभी फसलें" },
  "stock.clear": { en: "Clear", hi: "साफ़ करें" },
  "stock.stockCsv": { en: "Stock CSV", hi: "स्टॉक CSV" },
  "stock.txnCsv": { en: "Txn CSV", hi: "लेनदेन CSV" },
  "stock.lotsTxns": { en: "Lots / Txns", hi: "लॉट / लेनदेन" },
  "stock.farmerLotsTxns": { en: "Farmers / Lots / Txns", hi: "किसान / लॉट / लेनदेन" },
  "stock.aadhatComm": { en: "Aadhat Comm.", hi: "आढ़त कमीशन" },
  "stock.earnedViaBuyerDues": { en: "Earned (via Buyer Dues)", hi: "अर्जित (खरीदार बकाया से)" },
  "stock.cropGroupReinstated": { en: "Crop group reinstated", hi: "फसल समूह बहाल किया गया" },
  "stock.cropGroupArchived": { en: "Crop group archived", hi: "फसल समूह अभिलेखित किया गया" },
  "stock.farmerReinstated": { en: "Farmer reinstated", hi: "किसान बहाल किया गया" },
  "stock.saved": { en: "Saved", hi: "सहेजा गया" },
  "stock.saveFailed": { en: "Save Failed", hi: "सहेजने में विफल" },
  "stock.duplicateCard": { en: "A card for this farmer already exists on this date with the same vehicle number.", hi: "इस किसान का इस तारीख और उसी वाहन नंबर के साथ पहले से एक कार्ड मौजूद है।" },
  "stock.entrySavedSuccess": { en: "entry saved successfully", hi: "एंट्री सफलतापूर्वक सहेजी गई" },
  "stock.error": { en: "Error", hi: "त्रुटि" },
  "stock.farmerNameRequired": { en: "Farmer name is required", hi: "किसान का नाम आवश्यक है" },
  "stock.bagsExceedCapacity": { en: "Total lot bags exceeds vehicle capacity", hi: "कुल लॉट थैले वाहन क्षमता से अधिक हैं" },
  "stock.conflictForFarmer": { en: "A card for", hi: "किसान" },
  "stock.conflictNoVehicleDetail": { en: "already exists on {date} without a vehicle number. Please add a vehicle number to that card before creating a second card for the same farmer on this date.", hi: "{date} को बिना वाहन नंबर के पहले से मौजूद है। इसी किसान के लिए दूसरा कार्ड बनाने से पहले उस कार्ड में वाहन नंबर जोड़ें।" },
  "stock.conflictHasVehicleDetail": { en: "already exists on {date} (vehicle: {vehicle}). Make sure this new card has a different vehicle number.", hi: "{date} को पहले से मौजूद है (वाहन: {vehicle})। सुनिश्चित करें कि इस नए कार्ड का वाहन नंबर अलग हो।" },
  "stock.bidBagsExceedLot": { en: "Bid bags exceed lot bag count", hi: "बोली थैले लॉट थैलों से अधिक हैं" },
  "stock.vehicleCapacityReached": { en: "Vehicle capacity reached", hi: "वाहन क्षमता भर गई" },
  "stock.lotBagsFullyAllocated": { en: "Lot bags fully allocated", hi: "लॉट थैले पूरी तरह आवंटित हो गए" },
  "stock.noDataExport": { en: "No data to export", hi: "निर्यात के लिए कोई डेटा नहीं" },
  "stock.size": { en: "Size", hi: "साइज़" },
  "stock.variety": { en: "Variety", hi: "किस्म" },
  "stock.archive": { en: "Archive", hi: "अभिलेखित करें" },
  "stock.archiveCropGroupDesc": { en: "This crop group will be archived and excluded from all calculations.", hi: "यह फसल समूह अभिलेखित किया जाएगा और सभी गणनाओं से बाहर रखा जाएगा।" },
  "stock.archiveFarmerDesc": { en: "This farmer entry will be archived and excluded from all calculations.", hi: "यह किसान एंट्री अभिलेखित की जाएगी और सभी गणनाओं से बाहर रखी जाएगी।" },
  "stock.days": { en: "Days", hi: "दिन" },
  "stock.district": { en: "District", hi: "ज़िला" },
  "stock.earnedViaBuyer": { en: "Earned (via Buyer Dues)", hi: "अर्जित (खरीदार बकाया से)" },
  "stock.loadingStockEntries": { en: "Loading stock entries...", hi: "स्टॉक एंट्रियाँ लोड हो रही हैं..." },
  "stock.mandiStock": { en: "Mandi Stock", hi: "मंडी स्टॉक" },
  "stock.mandiStockDesc": { en: "Add farmers, lots, bids and weights in one place", hi: "किसान, लॉट, बोली और वज़न एक जगह जोड़ें" },
  "stock.months": { en: "Months", hi: "महीने" },
  "stock.printOverallBill": { en: "Print Overall Buyer Bill", hi: "खरीदार का कुल बिल प्रिंट करें" },
  "stock.shareOverallBill": { en: "Share Overall Bill", hi: "समग्र बिल शेयर करें" },
  "stock.printBidCopy": { en: "Print Bid Copy", hi: "बोली प्रति प्रिंट करें" },
  "stock.aadhatNakal": { en: "Aadhat Nakal", hi: "आढ़त नकल" },
  "stock.selectSingleDate": { en: "Please select a specific date to print Aadhat Nakal", hi: "आढ़त नकल प्रिंट करने के लिए कृपया एक तारीख चुनें" },
  "stock.noTransactions": { en: "No transactions found for the selected date", hi: "चयनित तारीख के लिए कोई लेनदेन नहीं मिला" },
  "stock.noBidCopyData": { en: "No saved lots found to print bid copy", hi: "बोली प्रति के लिए कोई सहेजी हुई खेप नहीं मिली" },
  "stock.reinstateFarmerDesc": { en: "This farmer entry and all its crop groups, lots, and bids will be included in all calculations again, including dues and payments.", hi: "यह किसान एंट्री और उसके सभी फसल समूह, लॉट और बोलियाँ फिर से सभी गणनाओं में शामिल की जाएँगी, जिसमें बकाया और भुगतान शामिल हैं।" },
  "stock.state": { en: "State", hi: "राज्य" },
  "stock.stock": { en: "Stock", hi: "स्टॉक" },
  "stock.tehsil": { en: "Tehsil", hi: "तहसील" },
  "stock.thisFarmer": { en: "this farmer", hi: "यह किसान" },
  "stock.totalBagsInVehicle": { en: "Total # of Bags", hi: "कुल थैले" },
  "stock.txn": { en: "Txn", hi: "लेनदेन" },
  "stock.vehicleNumber": { en: "Vehicle #", hi: "वाहन नंबर" },
  "stock.village": { en: "Village", hi: "गाँव" },
  "stock.deleteBidDesc": { en: "This bid will be permanently removed. The lot itself will remain.", hi: "यह बोली स्थायी रूप से हटा दी जाएगी। लॉट बना रहेगा।" },
  "stock.deleteBidWithTxnDesc": { en: "This bid, its linked transaction, and all associated payment and cash entries will be permanently deleted. This cannot be undone.", hi: "यह बोली, उससे जुड़ा लेनदेन, और सभी संबंधित भुगतान व नकद प्रविष्टियाँ स्थायी रूप से हटा दी जाएंगी। यह पूर्ववत नहीं किया जा सकता।" },
  "stock.receiptError": { en: "Receipt error", hi: "रसीद त्रुटि" },
  "stock.noTxnDataFound": { en: "No transaction data found", hi: "कोई लेनदेन डेटा नहीं मिला" },
  "stock.noTxnForBuyer": { en: "No transactions found for this buyer", hi: "इस खरीदार के लिए कोई लेनदेन नहीं मिला" },
  "stock.reinstateFailedCrop": { en: "Failed to reinstate crop group", hi: "फसल समूह बहाल करने में विफल" },
  "stock.archiveFailedCrop": { en: "Failed to archive crop group", hi: "फसल समूह अभिलेखित करने में विफल" },
  "stock.reinstateFailedFarmer": { en: "Failed to reinstate farmer", hi: "किसान बहाल करने में विफल" },
  "stock.archiveFailed": { en: "Archive Failed", hi: "अभिलेखित करने में विफल" },
  "stock.selectSingleDateBuyerCrop": { en: "Select a single date, buyer, and crop to print overall buyer bill", hi: "समग्र खरीदार बिल प्रिंट करने के लिए एक तिथि, खरीदार और फसल चुनें" },
  "stock.noTxnForBuyerCropDate": { en: "No transactions found for this buyer and crop on this date", hi: "इस तिथि पर इस खरीदार और फसल के लिए कोई लेनदेन नहीं मिला" },
  "stock.receiptSerialFailed": { en: "Could not assign receipt serial number. Please try again.", hi: "रसीद क्रमांक निर्धारित नहीं हो सका। कृपया पुनः प्रयास करें।" },
  "stock.vehiclePlaceholder": { en: "E.G. MP09AB1234", hi: "जैसे MP09AB1234" },
  "stock.varietyPlaceholder": { en: "e.g. Lal Pyaaz", hi: "जैसे लाल प्याज" },
  "stock.bagMarkaPlaceholder": { en: "e.g. ABC", hi: "जैसे ABC" },
  "stock.buyerNotSelected": { en: "Buyer not selected", hi: "खरीदार नहीं चुना गया" },
  "stock.buyerNotSelectedDesc": { en: "Please select a buyer from the dropdown. Bids without a matched buyer will not be saved", hi: "कृपया ड्रॉपडाउन से खरीदार चुनें। बिना मिलान वाली बोलियां सहेजी नहीं जाएंगी" },
  "stock.warning": { en: "Warning", hi: "चेतावनी" },
  "stock.failedDeleteBid": { en: "Failed to delete bid", hi: "बोली हटाने में विफल" },
  "stock.failedCreateBid": { en: "Failed to create bid", hi: "बोली बनाने में विफल" },
  "stock.failedUpdateBid": { en: "Failed to update bid", hi: "बोली अपडेट करने में विफल" },
  "stock.saveBlocked": { en: "Save blocked", hi: "सहेजना अवरुद्ध" },
  "stock.priceCannotBeZero": { en: "Price per kg cannot be 0 for a bid with an existing transaction", hi: "मौजूदा लेनदेन वाली बोली के लिए प्रति किलो मूल्य 0 नहीं हो सकता" },
  "stock.bagsCannotBeZero": { en: "Number of bags cannot be 0 for a bid with an existing transaction", hi: "मौजूदा लेनदेन वाली बोली के लिए बोरियों की संख्या 0 नहीं हो सकती" },
  "stock.weightCannotBeZero": { en: "Net weight cannot be 0 for a bid with an existing transaction", hi: "मौजूदा लेनदेन वाली बोली के लिए शुद्ध वज़न 0 नहीं हो सकता" },
  "stock.failedCreateTxn": { en: "Failed to create transaction", hi: "लेनदेन बनाने में विफल" },
  "stock.failedUpdateTxn": { en: "Failed to update transaction", hi: "लेनदेन अपडेट करने में विफल" },
  "stock.selectMode": { en: "Select", hi: "चुनें" },
  "stock.bags": { en: "Bags", hi: "बोरियां" },
  "stock.bid": { en: "Bid", hi: "बोली" },
  "stock.buyerName": { en: "Buyer Name", hi: "खरीदार का नाम" },
  "stock.buyerIdLabel": { en: "Buyer ID", hi: "खरीदार आईडी" },
  "stock.bidDbId": { en: "Bid DB ID", hi: "बोली DB आईडी" },
  "stock.txnDbId": { en: "Txn DB ID", hi: "लेनदेन DB आईडी" },
  "stock.paymentType": { en: "Payment Type", hi: "भुगतान प्रकार" },
  "stock.extraChargesFarmer": { en: "Extra Charges (Farmer)", hi: "अतिरिक्त शुल्क (किसान)" },
  "stock.extraChargesBuyer": { en: "Extra Charges (Buyer)", hi: "अतिरिक्त शुल्क (खरीदार)" },
  "stock.extraPerKgFarmer": { en: "Extra/kg (Farmer)", hi: "अतिरिक्त/किलो (किसान)" },
  "stock.extraPerKgBuyer": { en: "Extra/kg (Buyer)", hi: "अतिरिक्त/किलो (खरीदार)" },
  "stock.delete": { en: "Delete", hi: "हटाएं" },
  "stock.stateMP": { en: "Madhya Pradesh", hi: "मध्य प्रदेश" },
  "stock.stateGJ": { en: "Gujarat", hi: "गुजरात" },
  "stock.stateUP": { en: "Uttar Pradesh", hi: "उत्तर प्रदेश" },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem("mandi-mitra-lang");
      return (saved === "hi" ? "hi" : "en") as Language;
    } catch {
      return "en";
    }
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("mandi-mitra-lang", lang);
    } catch {}
  }, []);

  const t = useCallback((key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[language] || entry["en"] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
