import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "en" | "hi";

const translations: Record<string, Record<Language, string>> = {
  "app.name": { en: "Mandi Mitra", hi: "मंडी मित्र" },
  "app.tagline": { en: "Agricultural Marketplace Manager", hi: "कृषि बाज़ार प्रबंधक" },
  "app.loading": { en: "Loading...", hi: "लोड हो रहा है..." },

  "nav.dashboard": { en: "Dashboard", hi: "डैशबोर्ड" },
  "dash.farmersLotsTxns": { en: "Farmers / Lots / Txns", hi: "किसान / लॉट / लेनदेन" },
  "dash.farmerPayable": { en: "Farmer Payable", hi: "किसान देय" },
  "dash.buyerReceivable": { en: "Buyer Receivable", hi: "खरीदार प्राप्य" },
  "dash.mandiCommission": { en: "Mandi Commission", hi: "मण्डी कमीशन" },
  "dash.aadhatCommission": { en: "Aadhat Commission", hi: "आढ़त कमीशन" },
  "dash.receivablesByCrop": { en: "Receivables by Crop", hi: "फसल अनुसार प्राप्य" },
  "dash.buyerDuesDist": { en: "Buyer Dues Distribution", hi: "खरीदार बकाया वितरण" },
  "dash.farmerDueByDate": { en: "Farmer Payable Due by Date", hi: "तारीख अनुसार किसान बकाया" },
  "dash.buyerDueByDate": { en: "Buyer Receivable Due by Date", hi: "तारीख अनुसार खरीदार बकाया" },
  "dash.volumeByDate": { en: "Total Volume (Kg) by Date", hi: "तारीख अनुसार कुल वज़न (Kg)" },
  "dash.aadhatByDate": { en: "Aadhat Value by Date", hi: "तारीख अनुसार आढ़त मूल्य" },
  "dash.allCrops": { en: "All Crops", hi: "सभी फसलें" },
  "dash.allYears": { en: "All Years", hi: "सभी वर्ष" },
  "dash.due": { en: "Due", hi: "बकाया" },
  "dash.noData": { en: "No data", hi: "कोई डेटा नहीं" },
  "dash.chargeSettings": { en: "Charge Settings", hi: "शुल्क सेटिंग्स" },
  "dash.mandiCommPct": { en: "Mandi Commission (%)", hi: "मण्डी कमीशन (%)" },
  "dash.aadhatCommPct": { en: "Aadhat Commission (%)", hi: "आढ़त कमीशन (%)" },
  "dash.hammaliPerBag": { en: "Hammali (₹/bag)", hi: "हम्माली (₹/थैला)" },
  "dash.gradingPerBag": { en: "Grading (₹/bag)", hi: "ग्रेडिंग (₹/थैला)" },
  "dash.farmer": { en: "Farmer", hi: "किसान" },
  "dash.buyer": { en: "Buyer", hi: "खरीदार" },
  "dash.saveSettings": { en: "Save Settings", hi: "सेटिंग्स सहेजें" },
  "dash.saving": { en: "Saving...", hi: "सहेज रहे हैं..." },
  "dash.settingsSaved": { en: "Settings Saved", hi: "सेटिंग्स सहेजी गई" },
  "dash.settingsSavedDesc": { en: "Charge settings updated successfully", hi: "शुल्क सेटिंग्स सफलतापूर्वक अपडेट की गई" },
  "dash.error": { en: "Error", hi: "त्रुटि" },
  "dash.nYears": { en: "Years", hi: "वर्ष" },
  "dash.lineFarmerDue": { en: "Farmer Due", hi: "किसान बकाया" },
  "dash.lineBuyerDue": { en: "Buyer Due", hi: "खरीदार बकाया" },
  "dash.lineTotalVolume": { en: "Total Volume (Kg)", hi: "कुल वज़न (Kg)" },
  "dash.lineAadhatValue": { en: "Aadhat Value", hi: "आढ़त मूल्य" },
  "crop.potato": { en: "Potato", hi: "आलू" },
  "crop.onion": { en: "Onion", hi: "प्याज़" },
  "crop.garlic": { en: "Garlic", hi: "लहसुन" },
  "nav.dash": { en: "Dash", hi: "डैश" },
  "nav.stockEntry": { en: "Stock Entry", hi: "स्टॉक एंट्री" },
  "nav.stockRegister": { en: "Stock Register", hi: "स्टॉक रजिस्टर" },
  "nav.bidding": { en: "Bidding", hi: "बोली" },
  "nav.transactions": { en: "Transactions", hi: "लेनदेन" },
  "nav.cash": { en: "Cash", hi: "नकद" },
  "nav.farmerLedger": { en: "Farmer Ledger", hi: "किसान खाता" },
  "nav.buyerLedger": { en: "Buyer Ledger", hi: "खरीदार खाता" },
  "nav.entry": { en: "Entry", hi: "एंट्री" },
  "nav.register": { en: "Register", hi: "रजिस्टर" },
  "nav.txns": { en: "Txns", hi: "लेनदेन" },
  "nav.farmers": { en: "Farmers", hi: "किसान" },
  "nav.buyers": { en: "Buyers", hi: "खरीदार" },
  "nav.more": { en: "More", hi: "और" },
  "nav.logout": { en: "Logout", hi: "लॉगआउट" },

  "common.save": { en: "Save", hi: "सहेजें" },
  "common.cancel": { en: "Cancel", hi: "रद्द करें" },
  "common.edit": { en: "Edit", hi: "संपादन" },
  "common.delete": { en: "Delete", hi: "हटाएं" },
  "common.search": { en: "Search", hi: "खोजें" },
  "common.saving": { en: "Saving...", hi: "सहेज रहे हैं..." },
  "common.date": { en: "Date", hi: "दिनांक" },
  "common.name": { en: "Name", hi: "नाम" },
  "common.phone": { en: "Phone", hi: "फ़ोन" },
  "common.contact": { en: "Contact", hi: "संपर्क" },
  "common.address": { en: "Address", hi: "पता" },
  "common.village": { en: "Village", hi: "गाँव" },
  "common.tehsil": { en: "Tehsil", hi: "तहसील" },
  "common.district": { en: "District", hi: "जिला" },
  "common.state": { en: "State", hi: "राज्य" },
  "common.yes": { en: "Yes", hi: "हाँ" },
  "common.no": { en: "No", hi: "नहीं" },
  "common.all": { en: "All", hi: "सभी" },
  "common.active": { en: "Active", hi: "सक्रिय" },
  "common.inactive": { en: "Inactive", hi: "निष्क्रिय" },
  "common.notes": { en: "Notes", hi: "नोट्स" },
  "common.optional": { en: "Optional", hi: "वैकल्पिक" },
  "common.saveChanges": { en: "Save Changes", hi: "बदलाव सहेजें" },
  "common.actions": { en: "Actions", hi: "कार्रवाई" },
  "common.flag": { en: "Flag", hi: "फ्लैग" },
  "common.bags": { en: "bags", hi: "थैले" },
  "common.remaining": { en: "Remaining", hi: "शेष" },

  "stockEntry.title": { en: "Stock Entry", hi: "स्टॉक एंट्री" },
  "stockEntry.farmerDetails": { en: "Farmer Details", hi: "किसान विवरण" },
  "stockEntry.searchFarmer": { en: "Search Farmer (Name, Phone, Village)", hi: "किसान खोजें (नाम, फ़ोन, गाँव)" },
  "stockEntry.searchPlaceholder": { en: "Start typing farmer name, phone or village...", hi: "किसान का नाम, फ़ोन या गाँव टाइप करें..." },
  "stockEntry.newFarmer": { en: "New Farmer", hi: "नया किसान" },
  "stockEntry.farmerName": { en: "Farmer Name *", hi: "किसान का नाम *" },
  "stockEntry.mobileNumber": { en: "Mobile Number *", hi: "मोबाइल नंबर *" },
  "stockEntry.clearSelection": { en: "Clear", hi: "हटाएं" },
  "stockEntry.selectedFarmer": { en: "Selected Farmer", hi: "चयनित किसान" },
  "stockEntry.lotInfo": { en: "Lot Information", hi: "लॉट जानकारी" },
  "stockEntry.crop": { en: "Crop *", hi: "फसल *" },
  "stockEntry.size": { en: "Size *", hi: "साइज़ *" },
  "stockEntry.variety": { en: "Variety", hi: "किस्म" },
  "stockEntry.numberOfBags": { en: "No. of Bags *", hi: "थैलों की संख्या *" },
  "stockEntry.bagMarka": { en: "Bag Marka", hi: "बैग मार्का" },
  "stockEntry.vehicleNumber": { en: "Vehicle #", hi: "वाहन नं." },
  "stockEntry.bhadaRate": { en: "Bhada Rate/Bag", hi: "भाड़ा दर/थैला" },
  "stockEntry.initialWeight": { en: "Initial Total Weight (kg)", hi: "प्रारंभिक कुल वजन (किलो)" },
  "stockEntry.addLot": { en: "Add New Lot", hi: "नया लॉट जोड़ें" },
  "stockEntry.saveToRegister": { en: "Save to Stock Register", hi: "स्टॉक रजिस्टर में सहेजें" },
  "stockEntry.lot": { en: "Lot", hi: "लॉट" },
  "stockEntry.selectCrop": { en: "Select crop", hi: "फसल चुनें" },
  "stockEntry.selectSize": { en: "Select size", hi: "साइज़ चुनें" },
  "stockEntry.selectDistrict": { en: "Select district", hi: "जिला चुनें" },
  "stockEntry.mobilePlaceholder": { en: "10-digit mobile", hi: "10 अंक का मोबाइल" },
  "stockEntry.farmerNamePlaceholder": { en: "Farmer name", hi: "किसान का नाम" },

  "stockRegister.title": { en: "Stock Register", hi: "स्टॉक रजिस्टर" },
  "stockRegister.editLot": { en: "Edit Lot", hi: "लॉट संपादित करें" },
  "stockRegister.variety": { en: "Variety", hi: "किस्म" },
  "stockRegister.size": { en: "Size", hi: "साइज़" },
  "stockRegister.bagMarka": { en: "Bag Marka", hi: "बैग मार्का" },
  "stockRegister.vehicleNumber": { en: "Vehicle Number", hi: "वाहन नंबर" },
  "stockRegister.vehicleBhadaRate": { en: "Vehicle Bhada Rate (per bag)", hi: "वाहन भाड़ा दर (प्रति थैला)" },
  "stockRegister.initialWeight": { en: "Initial Total Weight (kg)", hi: "प्रारंभिक कुल वजन (किलो)" },
  "stockRegister.returnToFarmer": { en: "Return to Farmer", hi: "किसान को वापसी" },
  "stockRegister.returnConfirmTitle": { en: "Return Lot to Farmer?", hi: "लॉट किसान को वापस करें?" },
  "stockRegister.returnConfirmMsg": { en: "Are you sure you want to return this lot back to farmer?", hi: "क्या आप इस लॉट को किसान को वापस करना चाहते हैं?" },
  "stockRegister.returnPartialMsg": { en: "This lot is partially sold", hi: "यह लॉट आंशिक रूप से बिका है" },
  "stockRegister.returnUnsoldMsg": { en: "This lot has no sales. It will be marked as returned.", hi: "इस लॉट की कोई बिक्री नहीं है। इसे वापसी के रूप में चिह्नित किया जाएगा।" },
  "stockRegister.yesReturn": { en: "Yes, Return", hi: "हाँ, वापस करें" },
  "stockRegister.returning": { en: "Returning...", hi: "वापस कर रहे हैं..." },
  "stockRegister.searchPlaceholder": { en: "Search by farmer name, phone, Lot ID, SR#...", hi: "किसान नाम, फ़ोन, लॉट ID, SR# से खोजें..." },
  "stockRegister.farmerSearchPlaceholder": { en: "Search farmer name, phone, village...", hi: "किसान नाम, फ़ोन, गाँव खोजें..." },
  "stockRegister.allMonths": { en: "All", hi: "सभी" },
  "stockRegister.allDays": { en: "All Days", hi: "सभी दिन" },
  "stockRegister.clearFilters": { en: "Clear", hi: "हटाएँ" },
  "stockRegister.months": { en: "Month", hi: "माह" },
  "stockRegister.days": { en: "Day", hi: "दिन" },
  "stockRegister.nMonths": { en: "months", hi: "माह" },
  "stockRegister.nDays": { en: "days", hi: "दिन" },
  "stockRegister.noLots": { en: "No lots found for", hi: "कोई लॉट नहीं मिला" },
  "stockRegister.all": { en: "All", hi: "सभी" },
  "stockRegister.sold": { en: "Sold", hi: "बिका" },
  "stockRegister.unsoldFilter": { en: "Unsold", hi: "बिना बिका" },
  "stockRegister.unsold": { en: "Unsold", hi: "बिना बिका" },
  "stockRegister.soldOut": { en: "Sold Out", hi: "बिक गया" },
  "stockRegister.partiallySold": { en: "Partially Sold", hi: "आंशिक बिक्री" },
  "stockRegister.returned": { en: "Returned", hi: "वापसी" },
  "stockRegister.marka": { en: "Marka", hi: "मार्का" },
  "stockRegister.vehicle": { en: "Vehicle", hi: "वाहन" },
  "stockRegister.bhada": { en: "Bhada", hi: "भाड़ा" },
  "stockRegister.initWt": { en: "Init. Wt", hi: "प्रा. वजन" },

  "bidding.title": { en: "Bidding", hi: "बोली" },
  "bidding.bid": { en: "Bid", hi: "बोली" },
  "bidding.remainingBags": { en: "Remaining Bags", hi: "शेष थैले" },
  "bidding.existingBids": { en: "Existing Bids", hi: "मौजूदा बोलियाँ" },
  "bidding.newBid": { en: "New Bid", hi: "नई बोली" },
  "bidding.buyer": { en: "Buyer", hi: "खरीदार" },
  "bidding.selectBuyer": { en: "Select buyer", hi: "खरीदार चुनें" },
  "bidding.newBuyer": { en: "New Buyer", hi: "नया खरीदार" },
  "bidding.pricePerKg": { en: "Price/kg (Rs.)", hi: "दर/किलो (रु.)" },
  "bidding.numberOfBags": { en: "No. of Bags", hi: "थैलों की संख्या" },
  "bidding.addBid": { en: "Add Bid", hi: "बोली जोड़ें" },
  "bidding.noLots": { en: "No available lots for", hi: "कोई उपलब्ध लॉट नहीं" },
  "bidding.buyerName": { en: "Buyer name", hi: "खरीदार का नाम" },
  "bidding.phoneOptional": { en: "Phone (optional)", hi: "फ़ोन (वैकल्पिक)" },

  "transactions.title": { en: "Transactions", hi: "लेनदेन" },
  "transactions.editTransaction": { en: "Edit Transaction", hi: "लेनदेन संपादित करें" },
  "transactions.createTransaction": { en: "Create Transaction", hi: "लेनदेन बनाएं" },
  "transactions.selectBuyer": { en: "Select Buyer", hi: "खरीदार चुनें" },
  "transactions.totalWeight": { en: "Total Weight (kg)", hi: "कुल वजन (किलो)" },
  "transactions.netWeight": { en: "Net Weight (kg)", hi: "शुद्ध वजन (किलो)" },
  "transactions.hammali": { en: "Hammali (Rs./Bag)", hi: "हम्माली (रु./थैला)" },
  "transactions.grading": { en: "Grading (Rs.)", hi: "ग्रेडिंग (रु.)" },
  "transactions.aadhat": { en: "Aadhat %", hi: "आढ़त %" },
  "transactions.mandi": { en: "Mandi %", hi: "मण्डी %" },
  "transactions.buyer": { en: "Buyer", hi: "खरीदार" },
  "transactions.sellerFarmer": { en: "Seller (Farmer)", hi: "विक्रेता (किसान)" },
  "transactions.grossAmount": { en: "Gross Amount", hi: "कुल राशि" },
  "transactions.payableToFarmer": { en: "Payable to Farmer", hi: "किसान को देय" },
  "transactions.receivableFromBuyer": { en: "Receivable from Buyer", hi: "खरीदार से प्राप्य" },
  "transactions.updateTransaction": { en: "Update Transaction", hi: "लेनदेन अपडेट करें" },
  "transactions.returnToStockRegister": { en: "Return to Stock Register", hi: "स्टॉक रजिस्टर में वापसी" },
  "transactions.returnConfirmTitle": { en: "Return to Stock?", hi: "स्टॉक में वापस करें?" },
  "transactions.returnConfirmMsg": { en: "Are you sure you want to reverse this transaction?", hi: "क्या आप यह लेनदेन रद्द करना चाहते हैं?" },
  "transactions.yesReverse": { en: "Yes, Reverse", hi: "हाँ, रद्द करें" },
  "transactions.reversing": { en: "Reversing...", hi: "रद्द कर रहे हैं..." },
  "transactions.reversed": { en: "Reversed", hi: "रद्द" },
  "transactions.allMonths": { en: "All Months", hi: "सभी महीने" },
  "transactions.allDays": { en: "All Days", hi: "सभी दिन" },
  "transactions.allCrops": { en: "All Crops", hi: "सभी फसलें" },
  "transactions.farmer": { en: "Farmer", hi: "किसान" },
  "transactions.bagsTotal": { en: "bags total", hi: "कुल थैले" },
  "transactions.noBids": { en: "No bids or transactions yet. Complete bidding first.", hi: "अभी कोई बोली या लेनदेन नहीं। पहले बोली पूरी करें।" },
  "transactions.lot": { en: "Lot", hi: "लॉट" },

  "cash.title": { en: "Cash Management", hi: "नकद प्रबंधन" },
  "cash.subtitle": { en: "Track payments received and expenses", hi: "भुगतान प्राप्ति और खर्च ट्रैक करें" },
  "cash.buyer": { en: "Buyer", hi: "खरीदार" },
  "cash.farmer": { en: "Farmer", hi: "किसान" },
  "cash.others": { en: "Others", hi: "अन्य" },
  "cash.amount": { en: "Amount", hi: "राशि" },
  "cash.paymentMode": { en: "Payment Mode", hi: "भुगतान विधि" },
  "cash.noEntries": { en: "No cash flow entries yet", hi: "अभी तक कोई नकद प्रवाह एंट्री नहीं" },
  "cash.selectBuyer": { en: "Select buyer", hi: "खरीदार चुनें" },
  "cash.selectFarmer": { en: "Select farmer", hi: "किसान चुनें" },
  "cash.inward": { en: "Inflow", hi: "आवक" },
  "cash.outward": { en: "Outflow", hi: "जावक" },
  "cash.transfer": { en: "Transfer", hi: "हस्तांतरण" },
  "cash.inwardCash": { en: "Inward Cash", hi: "आवक नकद" },
  "cash.outwardCash": { en: "Outward Cash", hi: "जावक नकद" },
  "cash.outflowType": { en: "Outflow Type", hi: "जावक प्रकार" },
  "cash.farmerWithDues": { en: "Farmer (with dues)", hi: "किसान (बकाया सहित)" },
  "cash.filters": { en: "Filters", hi: "फ़िल्टर" },
  "cash.addBankFirst": { en: "Please add a bank account from Cash Settings before making transfers", hi: "ट्रांसफर करने से पहले कृपया कैश सेटिंग्स से बैंक खाता जोड़ें" },
  "cash.openSettings": { en: "Open Settings", hi: "सेटिंग्स खोलें" },
  "cash.cashFlowHistory": { en: "Cash Flow History", hi: "नकद प्रवाह इतिहास" },
  "cash.cashReceived": { en: "Cash Received", hi: "नकद प्राप्ति" },
  "cash.cashExpense": { en: "Cash Expense", hi: "नकद खर्च" },
  "cash.netCashInHand": { en: "Net Cash in Hand", hi: "हाथ में शेष नकद" },
  "cash.accountReceived": { en: "Account Received", hi: "खाता प्राप्ति" },
  "cash.accountExpense": { en: "Account Expense", hi: "खाता खर्च" },
  "cash.netInAccounts": { en: "Net in Accounts", hi: "खातों में शेष" },
  "cash.partyType": { en: "Party Type", hi: "पार्टी प्रकार" },
  "cash.buyerWithDues": { en: "Buyer (with dues)", hi: "खरीदार (बकाया सहित)" },
  "cash.paidOn": { en: "Paid On", hi: "भुगतान तिथि" },
  "cash.remarks": { en: "Remarks", hi: "टिप्पणी" },
  "cash.remarksPlaceholder": { en: "Any additional notes", hi: "अतिरिक्त नोट्स" },
  "cash.submit": { en: "Submit", hi: "जमा करें" },
  "cash.from": { en: "From", hi: "से" },
  "cash.to": { en: "To", hi: "को" },
  "cash.fromAccount": { en: "From Account", hi: "खाते से" },
  "cash.toAccount": { en: "To Account", hi: "खाते में" },
  "cash.selectAccount": { en: "Select account", hi: "खाता चुनें" },
  "cash.settings": { en: "Cash Settings", hi: "नकद सेटिंग्स" },
  "cash.cashInHandOpening": { en: "Cash in Hand (Opening Balance)", hi: "हाथ में नकद (प्रारंभिक शेष)" },
  "cash.bankAccounts": { en: "Bank Accounts", hi: "बैंक खाते" },
  "cash.addBankAccount": { en: "Add Bank Account", hi: "बैंक खाता जोड़ें" },
  "cash.addAccount": { en: "Add Account", hi: "खाता जोड़ें" },
  "cash.deleteAccount": { en: "Delete Bank Account", hi: "बैंक खाता हटाएं" },
  "cash.deleteAccountConfirm": { en: "Are you sure you want to delete the details of this bank account?", hi: "क्या आप इस बैंक खाते का विवरण हटाना चाहते हैं?" },
  "cash.bankAccount": { en: "Bank Account", hi: "बैंक खाता" },
  "cash.entryDetails": { en: "Entry Details", hi: "एंट्री विवरण" },
  "cash.category": { en: "Category", hi: "श्रेणी" },
  "cash.reverseEntry": { en: "Reverse Entry", hi: "एंट्री वापस करें" },
  "cash.reverseConfirm": { en: "This entry will be marked as reversed but not deleted. Are you sure?", hi: "यह एंट्री वापस चिह्नित की जाएगी लेकिन हटाई नहीं जाएगी। क्या आप सुनिश्चित हैं?" },
  "cash.reverse": { en: "Reverse", hi: "वापस करें" },
  "cash.partyName": { en: "Party Name", hi: "पार्टी नाम" },
  "cash.allParties": { en: "All Parties", hi: "सभी पार्टियां" },
  "cash.allTypes": { en: "All Types", hi: "सभी प्रकार" },

  "farmerLedger.title": { en: "Farmer Ledger", hi: "किसान खाता" },
  "farmerLedger.allYears": { en: "All Years", hi: "सभी वर्ष" },
  "farmerLedger.searchByName": { en: "Search By Name...", hi: "नाम से खोजें..." },
  "farmerLedger.searchByVillage": { en: "Search By Village...", hi: "गाँव से खोजें..." },
  "farmerLedger.showArchived": { en: "Show Archived", hi: "अभिलेख दिखाएं" },
  "farmerLedger.totalFarmers": { en: "Total Farmers", hi: "कुल किसान" },
  "farmerLedger.dueFarmers": { en: "# Due Farmers", hi: "बकाया किसान" },
  "farmerLedger.totalPayable": { en: "Total Payable", hi: "कुल देय" },
  "farmerLedger.totalDues": { en: "Total Dues", hi: "कुल बकाया" },
  "farmerLedger.farmerId": { en: "Farmer ID", hi: "किसान ID" },
  "farmerLedger.totalDue": { en: "Total Due", hi: "कुल बकाया" },
  "farmerLedger.editFarmer": { en: "Edit Farmer", hi: "किसान संपादित करें" },
  "farmerLedger.editDesc": { en: "Update farmer details. Duplicate detection will trigger merge if a match is found.", hi: "किसान विवरण अपडेट करें। डुप्लिकेट पाए जाने पर मर्ज होगा।" },
  "farmerLedger.negativeFlag": { en: "Negative Flag", hi: "नकारात्मक फ्लैग" },
  "farmerLedger.editHistory": { en: "Edit History", hi: "संपादन इतिहास" },
  "farmerLedger.noFarmers": { en: "No farmers found", hi: "कोई किसान नहीं मिला" },
  "farmerLedger.noArchived": { en: "No archived farmers found", hi: "कोई अभिलेख किसान नहीं मिला" },
  "farmerLedger.loadingFarmers": { en: "Loading farmers...", hi: "किसान लोड हो रहे हैं..." },
  "farmerLedger.reinstate": { en: "Reinstate", hi: "बहाल करें" },
  "farmerLedger.archive": { en: "Archive", hi: "अभिलेख" },

  "buyerLedger.title": { en: "Buyer Ledger", hi: "खरीदार खाता" },
  "buyerLedger.subtitle": { en: "Manage buyers and track dues", hi: "खरीदारों का प्रबंधन और बकाया ट्रैक करें" },
  "buyerLedger.buyerManagement": { en: "Buyer Management", hi: "खरीदार प्रबंधन" },
  "buyerLedger.searchName": { en: "Search Name...", hi: "नाम खोजें..." },
  "buyerLedger.addBuyer": { en: "Add Buyer", hi: "खरीदार जोड़ें" },
  "buyerLedger.buyerId": { en: "Buyer ID", hi: "खरीदार ID" },
  "buyerLedger.mandiCode": { en: "Mandi Code", hi: "मंडी कोड" },
  "buyerLedger.negative": { en: "Negative", hi: "नकारात्मक" },
  "buyerLedger.overallDue": { en: "Overall Due", hi: "कुल बकाया" },
  "buyerLedger.receivables": { en: "Receivables", hi: "प्राप्य" },
  "buyerLedger.editBuyer": { en: "Edit Buyer", hi: "खरीदार संपादित करें" },
  "buyerLedger.buyerCode": { en: "Buyer Code", hi: "खरीदार कोड" },
  "buyerLedger.openingBalance": { en: "Opening Balance", hi: "शुरुआती शेष" },
  "buyerLedger.negativeFlag": { en: "Negative Flag", hi: "नकारात्मक फ्लैग" },
  "buyerLedger.editHistory": { en: "Edit History", hi: "संपादन इतिहास" },
  "buyerLedger.addNewBuyer": { en: "Add New Buyer", hi: "नया खरीदार जोड़ें" },
  "buyerLedger.noBuyers": { en: "No buyers found", hi: "कोई खरीदार नहीं मिला" },
  "buyerLedger.overall": { en: "Overall", hi: "कुल" },
  "buyerLedger.receivable": { en: "Receivable", hi: "प्राप्य" },
  "buyerLedger.adding": { en: "Adding...", hi: "जोड़ रहे हैं..." },

  "login.title": { en: "Mandi Mitra", hi: "मंडी मित्र" },
  "login.userName": { en: "User Name", hi: "उपयोगकर्ता नाम" },
  "login.password": { en: "Password", hi: "पासवर्ड" },
  "login.login": { en: "Login", hi: "लॉगिन" },
  "login.signingIn": { en: "Signing in...", hi: "लॉगिन हो रहा है..." },
  "login.changePassword": { en: "Change Password", hi: "पासवर्ड बदलें" },
  "login.needHelp": { en: "Need Help? Please reach out to", hi: "मदद चाहिए? कृपया संपर्क करें" },
  "login.enterUsername": { en: "Enter Your Username", hi: "अपना उपयोगकर्ता नाम दर्ज करें" },
  "login.enterPassword": { en: "Enter password", hi: "पासवर्ड दर्ज करें" },

  "changePassword.title": { en: "Change Password", hi: "पासवर्ड बदलें" },
  "changePassword.registeredMobile": { en: "Registered Mobile Number", hi: "पंजीकृत मोबाइल नंबर" },
  "changePassword.currentPassword": { en: "Current Password", hi: "वर्तमान पासवर्ड" },
  "changePassword.newPassword": { en: "New Password", hi: "नया पासवर्ड" },
  "changePassword.confirmPassword": { en: "Confirm Password", hi: "पासवर्ड पुष्टि करें" },
  "changePassword.setNew": { en: "Set New Password", hi: "नया पासवर्ड सेट करें" },
  "changePassword.changing": { en: "Changing...", hi: "बदल रहे हैं..." },
  "changePassword.backToLogin": { en: "Back to Login", hi: "लॉगिन पर वापस जाएं" },
  "changePassword.forgotPassword": { en: "Forgot your password? Please contact", hi: "पासवर्ड भूल गए? कृपया संपर्क करें" },
  "changePassword.enterMobile": { en: "Enter your registered mobile number", hi: "अपना पंजीकृत मोबाइल नंबर दर्ज करें" },
  "changePassword.enterCurrent": { en: "Enter your current password", hi: "अपना वर्तमान पासवर्ड दर्ज करें" },
  "changePassword.enterNew": { en: "Enter new password", hi: "नया पासवर्ड दर्ज करें" },
  "changePassword.confirmNew": { en: "Confirm new password", hi: "नया पासवर्ड पुष्टि करें" },
  "changePassword.enterUsername": { en: "Enter your username", hi: "अपना उपयोगकर्ता नाम दर्ज करें" },

  "admin.title": { en: "Admin Panel", hi: "एडमिन पैनल" },
  "admin.subtitle": { en: "Manage merchants and users", hi: "व्यापारी और उपयोगकर्ता प्रबंधित करें" },
  "admin.merchants": { en: "Merchants", hi: "व्यापारी" },
  "admin.users": { en: "Users", hi: "उपयोगकर्ता" },
  "admin.addMerchant": { en: "Add Merchant", hi: "व्यापारी जोड़ें" },
  "admin.searchMerchants": { en: "Search Merchants...", hi: "व्यापारी खोजें..." },
  "admin.merchantId": { en: "Merchant ID", hi: "व्यापारी ID" },
  "admin.businessName": { en: "Business Name *", hi: "व्यापार का नाम *" },
  "admin.contactNumber": { en: "Contact Number", hi: "संपर्क नंबर" },
  "admin.status": { en: "Status", hi: "स्थिति" },
  "admin.editMerchant": { en: "Edit Merchant", hi: "व्यापारी संपादित करें" },
  "admin.createMerchant": { en: "Create a new merchant/business account", hi: "नया व्यापारी/व्यापार खाता बनाएं" },
  "admin.updateMerchant": { en: "Update merchant details for", hi: "व्यापारी विवरण अपडेट करें" },
  "admin.update": { en: "Update", hi: "अपडेट" },
  "admin.confirm": { en: "Confirm", hi: "पुष्टि करें" },
  "admin.processing": { en: "Processing...", hi: "प्रक्रिया में..." },
  "admin.adminPassword": { en: "Admin Password *", hi: "एडमिन पासवर्ड *" },
  "admin.resetPassword": { en: "Reset Password *", hi: "रीसेट पासवर्ड *" },
  "admin.searchUsers": { en: "Search Users...", hi: "उपयोगकर्ता खोजें..." },
  "admin.addUser": { en: "Add User", hi: "उपयोगकर्ता जोड़ें" },
  "admin.noMerchants": { en: "No merchants found", hi: "कोई व्यापारी नहीं मिला" },
  "admin.noUsers": { en: "No users found", hi: "कोई उपयोगकर्ता नहीं मिला" },
  "admin.manageMerchants": { en: "Manage all registered merchants/businesses", hi: "सभी पंजीकृत व्यापारी/व्यापार प्रबंधित करें" },
  "admin.manageUsers": { en: "Manage all user accounts", hi: "सभी उपयोगकर्ता खाते प्रबंधित करें" },

  "language.english": { en: "English", hi: "English" },
  "language.hindi": { en: "हिंदी", hi: "हिंदी" },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem("mandi-mitra-lang");
      return (saved === "hi" ? "hi" : "en") as Language;
    } catch {
      return "en";
    }
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("mandi-mitra-lang", lang);
    } catch {}
  }, []);

  const t = useCallback((key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[language] || entry["en"] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
